title: webflaix
author: Florian Zschocke
email: flaix@example.com
description: > # this means to ignore newlines until "baseurl:"
  The weblog of a forgetful soul. Full of stuff that once was deemed
  useful enough to remember - electronically.

# social links
twitter_username: flaix
github_username:  fzs

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
